package com.homework.estate_project.entity.enums;

public enum EstateFeature {
    IN_CONSTRUCTION,
    ELEVATOR,
    OPEN_PARKING,
    GARAGE,
    BARTER,
    SECURITY,
    CONTROL_OF_ACCESS,
    CLOSED_COMPLEX,
    SANITIZED,
    VIDEO_SURVEILLANCE,
    NEEDS_RENOVATION,
    FURNISHED,
    OPERATING_BUSINESS,
    PARK_VIEW, CITY_VIEW, NATURE_VIEW,
    CENTRAL_HEATING, LOCAL_HEATING, NATURE_GAS,
    EAST, WEST,NORTH,SOUTH, NORTHEAST,NORTHWEST,SOUTHEAST,SOUTHWEST,
    HIGH_CEILINGS, SLOPED_CEILINGS,
    METRO, PUBLIC_TRANSPORT_STOP,
    HYPERMARKET,
    BALCONY,
    SPACIOUS_ROOMS,
    ATTIC,BASEMENT
}
