package com.homework.estate_project.entity.enums;


public enum Location {

    // Sofia
    SOFIA_ABDOVITSA,
    SOFIA_BANISHORA, SOFIA_BELITE_BREZI, SOFIA_BENKOVSKI, SOFIA_BOROVO, SOFIA_BOTUNEC, SOFIA_BOYANA, SOFIA_BUNKERA, SOFIA_BUKSTON,
    SOFIA_VITOSHA, SOFIA_VRAZDEBNA, SOFIA_VRUBNICA, SOFIA_VRUBNICA_1, SOFIA_VRUBNICA_2,
    SOFIA_GEO_MILEV, SOFIA_GORNA_BANYA, SOFIA_GORUBLYANE, SOFIA_GOTSE_DELCHEV,
    SOFIA_DIANABAD, SOFIA_DRAGALEVTSI, SOFIA_DRUZBA_1, SOFIA_DRUZBA_2, SOFIA_DARVENITSA,
    SOFIA_ZAPADEN_PARK, SOFIA_ZAHARNA_FABRIKA, SOFIA_ZONA_B5, SOFIA_ZONA_B18, SOFIA_ZONA_B19,
    SOFIA_IVAN_VAOZV, SOFIA_IZGREV, SOFIA_IZTOK, SOFIA_ILINDEN, SOFIA_ILIYANCI,
    SOFIA_KINOCENTAR, SOFIA_KNAZHEVO, SOFIA_KRASNA_POLYANA, SOFIA_KRASNO_SELO, SOFIA_KREMIKOVTSI, SOFIA_KRIVA_REKA, SOFIA_KRASTOVA_VADA,
    SOFIA_LAGERA, SOFIA_LEVSKI, SOFIA_LOZENETS, SOFIA_LIULIN1, SOFIA_LIULIN2, SOFIA_LIULIN3, SOFIA_LIULIN4, SOFIA_LIULIN5, SOFIA_LIULIN6, SOFIA_LIULIN7, SOFIA_LIULIN8, SOFIA_LIULIN9, SOFIA_LIULIN10, SOFIA_LIULIN_CENTAR,
    SOFIA_MALASHEVTSI, SOFIA_MALINOVA_DOLINA, SOFIA_MANASTIRSKI_LIVADI, SOFIA_MLADOST1, SOFIA_MLADOST2, SOFIA_MLADOST3, SOFIA_MLADOST4, SOFIA_MLADOST1A, SOFIA_MODERNO_PREDGRADIE, SOFIA_MOTOPISTA, SOFIA_MUSAGENITSA,
    SOFIA_NADEZHDA1, SOFIA_NADEZHDA2, SOFIA_NADEZHDA3, SOFIA_NADEZHDA4,
    SOFIA_OBELYA, SOFIA_OVCHA_KUPEL1, SOFIA_OVCHA_KUPEL2, SOFIA_ORLANDOVCI,
    SOFIA_PAVLOVO, SOFIA_PODUYANE, SOFIA_POLIGONA,
    SOFIA_RAZSADNIKA, SOFIA_REDUTA, SOFIA_REPUBLIKA,
    SOFIA_SVETA_TROICA, SOFIA_SVOBODA, SOFIA_SERDIKA, SOFIA_SESLAVTSI, SOFIA_SIMEONOVO, SOFIA_SLAVIYA, SOFIA_SLATINA, SOFIA_STEFAN_KARADZHA, SOFIA_STRELBISHTE, SOFIA_STUDENTSKI_GRAD, SOFIA_SUHATA_REKA, SOFIA_SUHODOL,
    SOFIA_TREBITCH, SOFIA_TRIAGALNIKA,
    SOFIA_FAKULTETA, SOFIA_FILIPOVTSI, SOFIA_FONDOVI_ZHILISHTA,
    SOFIA_HADZI_DIMITAR, SOFIA_HIPODRUMA, SOFIA_HLADILNIKA, SOFIA_HRISTO_BOTEV,
    SOFIA_CENTAR, SOFIA_CHELOPECHENE,
    SOFIA_IUZHEN_PARK,
    SOFIA_YAVOROV,

    // Gabrovo
    GABROVO_BAKOITSI,GABROVO_BELENCI,GABROVO_BICHKINYA,GABROVO_BOLTATA,GABROVO_BOROVO,
    GABROVO_CHARKOVO,GABROVO_DYADO_DYANKO,GABROVO_ETARA,GABROVO_CENTAR,GABROVO_GARATA,
    GABROVO_GATCHEVTSI,GABROVO_GOLO_BARDO,GABROVO_HADZHITSONEV_MOST,GABROVO_ILEVTSI,GABROVO_INSTRUMENT,
    GABROVO_IOVCHOVTSI,GABROVO_KIEVTSI,GABROVO_KOLELOTO,GABROVO_KRYAKOVTSI,GABROVO_LAKATA,GABROVO_LISEC,
    GABROVO_LYUBOVO,GABROVO_MLADOST,GABROVO_NEDEVCI,GABROVO_NEGENTSI,GABROVO_NOVA_MAHALA,GABROVO_QBALKA,
    GABROVO_RADICHEVEC,GABROVO_RUSEVTSI,GABROVO_SHENINI,GABROVO_SHIVAROV_MOST,GABROVO_SIRMANI,GABROVO_TRANETO,
    GABROVO_TRENDAFIL1,GABROVO_TRENDAFIL2,GABROVO_VLECHEVTSI,GABROVO_VOINOVO
}
